services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: true
      bind:

  CoreBundle\:
    resource: '../../../CoreBundle/*'
    exclude: '../../../CoreBundle/{Entity, Repository}'