imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    dbal:
        driver:   pdo_mysql
        server_version: 5.7
    orm:
       metadata_cache_driver: array
       query_cache_driver: array

swiftmailer:
    transport: smtp
    host: localhost
    port: 1025
    username: null
    password: null